foreground #f4e8dc
background #050403
selection_foreground #050403
selection_background #ff5a00
cursor #ff6a00
cursor_text_color #050403
url_color #ff9a3d

active_tab_foreground #050403
active_tab_background #ff5a00
inactive_tab_foreground #a88b78
inactive_tab_background #14100d

color0  #090705
color8  #5a3728

color1  #ff3500
color9  #ff6a00

color2  #6be675
color10 #a4ff9b

color3  #ffb000
color11 #ffd166

color4  #cf4f2e
color12 #ff7a3d

color5  #d95f2a
color13 #ff9a3d

color6  #e0a070
color14 #ffd2a6

color7  #f4e8dc
color15 #fff4e8
