#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
source "$SCRIPT_DIR/lib/common.sh"

ROOT_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd)
TOOLS_JSON="$ROOT_DIR/data/tools.json"
CLI_DOCS="$ROOT_DIR/scripts/cento_interactive.py"
CLI_INTERACTIVE="$ROOT_DIR/scripts/cento_interactive.sh"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/cento"
CONFIG_FILE="$CONFIG_DIR/aliases.sh"
CONFIG_TEMPLATE="$ROOT_DIR/templates/cento/aliases.sh"
COMPLETION_TEMPLATE="$ROOT_DIR/scripts/completion/_cento"
COMPLETION_DIR="$CONFIG_DIR/completions"
COMPLETION_FILE="$COMPLETION_DIR/_cento"
ZSH_INIT_FILE="$CONFIG_DIR/init.zsh"
ZSHRC_FILE="$HOME/.zshrc"
ZSH_INIT_START="# >>> cento init >>>"
ZSH_INIT_END="# <<< cento init <<<"

declare -A CENTO_ALIAS_COMMANDS=()
declare -A CENTO_ALIAS_DESCRIPTIONS=()

usage() {
    cat <<'USAGE'
Usage: cento <command> [args...]

Built-ins:
  help                 Show this help
  interactive          Open Bubble Tea docs and command browser
  docs [ENTRY]         Print CLI docs from the canonical JSON source
  tools                List registered cento tools
  aliases              List configured user aliases
  conf [--path]        Open or print the cento config file
  completion zsh       Print Zsh completion for cento
  install [zsh]        Install cento shell integration
  run TOOL [args...]   Run a registered tool by id

Routing:
  cento TOOL [args...]    Run a registered tool directly
  cento ALIAS [args...]   Run a configured alias directly

Examples:
  cento interactive
  cento docs
  cento docs conf
  cento tools
  cento aliases
  cento conf
  cento conf --path
  cento completion zsh
  cento install zsh
  cento mcp doctor
  cento mcp docs
  cento scan --query "mcp"
  cento kitty-theme-manager --list-custom
  cento monk
  cento cyber
USAGE
}

expand_tilde() {
    local value=$1
    if [[ "$value" == ~* ]]; then
        printf '%s\n' "${value/#\~/$HOME}"
        return
    fi
    printf '%s\n' "$value"
}

ensure_config_file() {
    cento_ensure_dir "$CONFIG_DIR"
    if [[ ! -f "$CONFIG_FILE" ]]; then
        cp "$CONFIG_TEMPLATE" "$CONFIG_FILE"
    fi
}

cento_alias() {
    local name=${1:-}
    local description=""
    shift || true

    [[ -n "$name" ]] || cento_die "Alias name is required"

    if [[ ${1:-} == "--description" ]]; then
        description=${2:-}
        shift 2 || true
    fi

    [[ ${1:-} == "--" ]] || cento_die "Alias '$name' must use '--' before the command"
    shift
    [[ $# -gt 0 ]] || cento_die "Alias '$name' must define a command"

    local serialized
    printf -v serialized '%q ' "$@"
    CENTO_ALIAS_COMMANDS["$name"]=${serialized% }
    CENTO_ALIAS_DESCRIPTIONS["$name"]=$description
}

load_config() {
    ensure_config_file
    CENTO_ALIAS_COMMANDS=()
    CENTO_ALIAS_DESCRIPTIONS=()
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
}

choose_editor() {
    local candidate
    for candidate in "${VISUAL:-}" "${EDITOR:-}" nvim vim nano vi; do
        [[ -n "$candidate" ]] || continue
        if cento_have_cmd "$candidate"; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

open_config() {
    ensure_config_file
    if [[ ${1:-} == "--path" ]]; then
        printf '%s\n' "$CONFIG_FILE"
        return 0
    fi

    local editor
    editor=$(choose_editor) || cento_die "No editor found via VISUAL, EDITOR, nvim, vim, nano, or vi"
    exec "$editor" "$CONFIG_FILE"
}

list_aliases() {
    load_config

    if [[ ${#CENTO_ALIAS_COMMANDS[@]} -eq 0 ]]; then
        printf 'No cento aliases configured. Edit %s\n' "$CONFIG_FILE"
        return 0
    fi

    local name
    while IFS= read -r name; do
        printf '%-18s  %-32s  %s\n' \
            "$name" \
            "${CENTO_ALIAS_DESCRIPTIONS[$name]:-}" \
            "${CENTO_ALIAS_COMMANDS[$name]}"
    done < <(printf '%s\n' "${!CENTO_ALIAS_COMMANDS[@]}" | sort)
}

list_tools() {
    python3 - "$TOOLS_JSON" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
data = json.loads(path.read_text())
for tool in sorted(data["tools"], key=lambda item: item["id"]):
    print(f"{tool['id']:<22}  {tool['name']:<24}  {tool.get('description', '')}")
PY
}

print_zsh_completion() {
    [[ -f "$COMPLETION_TEMPLATE" ]] || cento_die "Completion template missing: $COMPLETION_TEMPLATE"
    cat "$COMPLETION_TEMPLATE"
}

write_zsh_completion() {
    [[ -f "$COMPLETION_TEMPLATE" ]] || cento_die "Completion template missing: $COMPLETION_TEMPLATE"
    cento_ensure_dir "$COMPLETION_DIR"
    cat "$COMPLETION_TEMPLATE" > "$COMPLETION_FILE"
}

write_zsh_init() {
    cento_ensure_dir "$CONFIG_DIR"
    cat > "$ZSH_INIT_FILE" <<EOF_ZSH
# Generated by cento install zsh
if [[ -d "$COMPLETION_DIR" ]]; then
  case " \${fpath[*]} " in
    *" $COMPLETION_DIR "*) ;;
    *) fpath=("$COMPLETION_DIR" \$fpath) ;;
  esac

  if ! typeset -f compdef >/dev/null 2>&1; then
    autoload -Uz compinit
    compinit
  fi

  autoload -Uz _cento
  compdef _cento cento
fi
EOF_ZSH
}

ensure_zshrc_sources_cento() {
    touch "$ZSHRC_FILE"
    if grep -Fq "$ZSH_INIT_START" "$ZSHRC_FILE"; then
        return 0
    fi

    cat >> "$ZSHRC_FILE" <<EOF_ZSHRC

$ZSH_INIT_START
if [[ -f "$ZSH_INIT_FILE" ]]; then
  source "$ZSH_INIT_FILE"
fi
$ZSH_INIT_END
EOF_ZSHRC
}

install_zsh_integration() {
    write_zsh_completion
    write_zsh_init
    ensure_zshrc_sources_cento
    printf 'Installed cento Zsh integration.\n'
    printf 'Completion: %s\n' "$COMPLETION_FILE"
    printf 'Init: %s\n' "$ZSH_INIT_FILE"
    printf 'Shell config: %s\n' "$ZSHRC_FILE"
}

handle_completion() {
    local shell_name=${1:-}
    case "$shell_name" in
        zsh)
            print_zsh_completion
            ;;
        *)
            cento_die "Usage: cento completion zsh"
            ;;
    esac
}

handle_install() {
    local target=${1:-zsh}
    case "$target" in
        zsh)
            install_zsh_integration
            ;;
        *)
            cento_die "Usage: cento install [zsh]"
            ;;
    esac
}

run_cli_docs() {
    [[ -f "$CLI_DOCS" ]] || cento_die "CLI docs backend missing: $CLI_DOCS"
    exec python3 "$CLI_DOCS" "$@"
}

run_cli_interactive() {
    [[ -f "$CLI_INTERACTIVE" ]] || cento_die "CLI interactive launcher missing: $CLI_INTERACTIVE"
    exec "$CLI_INTERACTIVE" "$@"
}

handle_docs() {
    if [[ $# -eq 0 ]]; then
        run_cli_docs --overview
    fi
    if [[ ${1:-} != -* ]]; then
        local entry=$1
        shift
        run_cli_docs --entry "$entry" "$@"
    fi
    run_cli_docs "$@"
}

handle_interactive() {
    run_cli_interactive "$@"
}

resolve_tool() {
    local tool_id=$1
    python3 - "$TOOLS_JSON" "$tool_id" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
tool_id = sys.argv[2]
data = json.loads(path.read_text())
for tool in data["tools"]:
    if tool["id"] == tool_id:
        print(tool.get("kind", ""))
        print(tool.get("wrapper", ""))
        print(tool.get("entrypoint", ""))
        raise SystemExit(0)
raise SystemExit(1)
PY
}

current_platform() {
    case "$(uname -s)" in
        Linux)
            printf 'linux\n'
            ;;
        Darwin)
            printf 'macos\n'
            ;;
        *)
            uname -s | tr '[:upper:]' '[:lower:]'
            ;;
    esac
}

ensure_tool_platform() {
    local tool_id=$1
    local platform
    platform=$(current_platform)

    python3 - "$TOOLS_JSON" "$tool_id" "$platform" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
tool_id = sys.argv[2]
platform = sys.argv[3]
data = json.loads(path.read_text())

for tool in data["tools"]:
    if tool["id"] != tool_id:
        continue
    platforms = tool.get("platforms") or []
    if not platforms or platform in platforms:
        raise SystemExit(0)
    print(
        f"Tool '{tool_id}' is not available on {platform}; supported platforms: {', '.join(platforms)}",
        file=sys.stderr,
    )
    raise SystemExit(2)

raise SystemExit(1)
PY
}

tool_exists() {
    python3 - "$TOOLS_JSON" "$1" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
tool_id = sys.argv[2]
data = json.loads(path.read_text())
raise SystemExit(0 if any(tool["id"] == tool_id for tool in data["tools"]) else 1)
PY
}

run_tool() {
    local tool_id=$1
    shift || true

    local kind wrapper entrypoint
    mapfile -t _tool_meta < <(resolve_tool "$tool_id")
    [[ ${#_tool_meta[@]} -ge 3 ]] || cento_die "Unknown tool: $tool_id"
    ensure_tool_platform "$tool_id" || exit $?
    kind=${_tool_meta[0]:-}
    wrapper=${_tool_meta[1]:-}
    entrypoint=${_tool_meta[2]:-}

    if [[ -n "$wrapper" ]]; then
        wrapper=$(expand_tilde "$wrapper")
        if [[ -x "$wrapper" ]]; then
            exec "$wrapper" "$@"
        fi
    fi

    entrypoint=${entrypoint#./}
    local target="$ROOT_DIR/$entrypoint"
    [[ -f "$target" ]] || cento_die "Tool entrypoint missing: $target"

    case "$kind" in
        python)
            exec python3 "$target" "$@"
            ;;
        shell|bash|sh|*)
            exec "$target" "$@"
            ;;
    esac
}

run_alias_with_args() {
    local alias_name=$1
    shift || true

    load_config
    [[ -n ${CENTO_ALIAS_COMMANDS[$alias_name]:-} ]] || cento_die "Unknown alias: $alias_name"

    local serialized=${CENTO_ALIAS_COMMANDS[$alias_name]}
    local -a extra=("$@")
    eval "set -- $serialized"
    exec "$@" "${extra[@]}"
}

main() {
    local command=${1:-help}
    if [[ $# -gt 0 ]]; then
        shift
    fi

    case "$command" in
        help|-h|--help)
            usage
            ;;
        interactive)
            handle_interactive "$@"
            ;;
        docs)
            handle_docs "$@"
            ;;
        tools)
            list_tools
            ;;
        aliases)
            list_aliases
            ;;
        conf)
            open_config "$@"
            ;;
        completion)
            handle_completion "$@"
            ;;
        install)
            handle_install "$@"
            ;;
        run)
            [[ $# -gt 0 ]] || cento_die "Usage: cento run TOOL [args...]"
            local tool_id=$1
            shift
            run_tool "$tool_id" "$@"
            ;;
        *)
            load_config
            if [[ -n ${CENTO_ALIAS_COMMANDS[$command]:-} ]]; then
                run_alias_with_args "$command" "$@"
            elif tool_exists "$command"; then
                run_tool "$command" "$@"
            else
                cento_die "Unknown cento command, alias, or tool: $command"
            fi
            ;;
    esac
}

main "$@"
