#!/usr/bin/env python3

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def esc(value: Any) -> str:
    return html.escape(str(value or ""), quote=True)


def badge_slug(value: Any) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", str(value or "").strip().lower()).strip("-")
    return slug or "neutral"


def badge_text(value: Any) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    return re.sub(r"[-_]+", " ", text).upper()


def load_manifest(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"manifest not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise SystemExit("manifest root must be an object")
    return payload


def cards(items: list[dict[str, Any]]) -> str:
    output = []
    for item in items:
        href = esc(item.get("href") or "#")
        class_name = "card primary" if item.get("primary") else "card"
        title = esc(item.get("title"))
        description = esc(item.get("description"))
        code = item.get("code")
        badge = item.get("badge")
        lines = [
            f'          <a class="{class_name}" href="{href}">',
        ]
        if badge:
            lines.append(
                f'            <div class="card-badge"><span class="pill pill-{badge_slug(badge)}">{esc(badge_text(badge))}</span></div>'
            )
        lines.append(f"            <h3>{title}</h3>")
        if code:
            lines.append(f"            <code>{esc(code)}</code>")
        lines.extend(
            [
                f"            <span>{description}</span>",
                "          </a>",
            ]
        )
        output.append("\n".join(lines))
    return "\n".join(output)


def story_status(items: list[dict[str, Any]]) -> str:
    output = []
    for item in items:
        output.append(
            f"""
          <div class="status-item"><strong>{esc(item.get("label"))}</strong><span>{esc(item.get("description"))}</span></div>"""
        )
    return "\n".join(output)


def commands(items: list[str]) -> str:
    return "\n".join(f"          <code>{esc(item)}</code>" for item in items)


def review_items(items: list[str]) -> str:
    return "\n".join(f"          <li>{esc(item)}</li>" for item in items)


def render(manifest: dict[str, Any]) -> str:
    title = esc(manifest.get("title") or "Cento Deliverables")
    subtitle = esc(manifest.get("subtitle") or "Project links, screenshots, validation evidence, and review status.")
    badge = esc(manifest.get("badge") or "Ready")
    footer = esc(manifest.get("footer") or "Generated by scripts/deliverables_hub.py")
    use_first = cards(manifest.get("use_first") or [])
    stories = story_status(manifest.get("stories") or [])
    validation_results = cards(manifest.get("validation_results") or [])
    command_list = commands(manifest.get("commands") or [])
    screenshot_cards = cards(manifest.get("screenshots") or [])
    review = review_items(manifest.get("review") or [])
    validation_results_section = ""
    if validation_results:
        validation_results_section = f"""
      <section>
        <h2>Validation Results</h2>
        <div class="cards">
{validation_results}
        </div>
      </section>"""

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    :root {{
      color-scheme: dark;
      --bg: #070809;
      --panel: #12161a;
      --line: #29313a;
      --text: #f4f6f7;
      --muted: #a9b3bd;
      --orange: #ff7900;
      --green: #35d273;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: radial-gradient(circle at 50% -120px, rgba(255,121,0,.16), transparent 420px), var(--bg);
      color: var(--text);
      font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    main {{
      width: min(1040px, calc(100vw - 28px));
      margin: 0 auto;
      padding: 28px 0 42px;
    }}
    header {{
      display: grid;
      grid-template-columns: 1fr auto;
      gap: 18px;
      align-items: start;
      padding-bottom: 18px;
      border-bottom: 1px solid var(--line);
      margin-bottom: 16px;
    }}
    h1, h2, h3, p {{ margin: 0; }}
    h1 {{ font-size: 34px; line-height: 1.08; }}
    h2 {{
      color: var(--orange);
      font-size: 13px;
      letter-spacing: .08em;
      text-transform: uppercase;
      margin-bottom: 10px;
    }}
    h3 {{ font-size: 18px; margin-bottom: 4px; }}
    .sub {{ color: var(--muted); margin-top: 8px; font-size: 17px; }}
    .badge {{
      min-width: 122px;
      padding: 12px;
      border: 1px solid rgba(53,210,115,.45);
      border-radius: 8px;
      background: rgba(53,210,115,.08);
      text-align: center;
      color: var(--green);
      font-weight: 800;
    }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(12, 1fr);
      gap: 12px;
    }}
    section, .card {{
      border: 1px solid var(--line);
      border-radius: 8px;
      background: linear-gradient(180deg, rgba(255,255,255,.045), rgba(255,255,255,.02));
    }}
    section {{
      grid-column: span 12;
      padding: 16px;
    }}
    .cards {{
      display: grid;
      grid-template-columns: repeat(3, minmax(0, 1fr));
      gap: 10px;
    }}
    .card {{
      display: block;
      min-height: 126px;
      padding: 14px;
      color: var(--text);
      text-decoration: none;
    }}
    .card-badge {{
      display: flex;
      justify-content: flex-end;
      margin-bottom: 10px;
      min-height: 20px;
    }}
    .card.primary {{
      border-color: rgba(255,121,0,.5);
      background: linear-gradient(180deg, rgba(255,121,0,.18), rgba(255,121,0,.055));
    }}
    .card span {{
      display: block;
      color: var(--muted);
      margin-top: 6px;
    }}
    .pill {{
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-height: 20px;
      padding: 2px 8px;
      border: 1px solid var(--line);
      border-radius: 999px;
      background: rgba(255,255,255,.05);
      color: var(--muted);
      font-size: 11px;
      font-weight: 800;
      letter-spacing: .08em;
      text-transform: uppercase;
      white-space: nowrap;
    }}
    .pill-neutral {{
      border-color: rgba(255,255,255,.18);
      color: var(--muted);
    }}
    .pill-pass {{
      border-color: rgba(53,210,115,.45);
      background: rgba(53,210,115,.08);
      color: var(--green);
    }}
    .pill-fail, .pill-blocked {{
      border-color: rgba(255,93,93,.45);
      background: rgba(255,93,93,.08);
      color: #ff8d8d;
    }}
    .pill-warn {{
      border-color: rgba(255,193,7,.45);
      background: rgba(255,193,7,.08);
      color: #ffd15a;
    }}
    .pill-ready, .pill-running, .pill-done, .pill-report {{
      border-color: rgba(255,121,0,.45);
      background: rgba(255,121,0,.08);
      color: #ffd7b0;
    }}
    .pill-no-model {{
      border-color: rgba(108,183,255,.45);
      background: rgba(108,183,255,.08);
      color: #9fd2ff;
    }}
    .card code, .commands code {{
      display: inline-block;
      max-width: 100%;
      overflow-wrap: anywhere;
      padding: 2px 5px;
      border: 1px solid var(--line);
      border-radius: 5px;
      background: #080a0c;
      color: #ffd7b0;
    }}
    .commands {{
      display: grid;
      gap: 8px;
    }}
    .commands code {{
      display: block;
      padding: 10px;
    }}
    .status-list {{
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 8px;
    }}
    .status-item {{
      min-height: 74px;
      padding: 10px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: rgba(255,255,255,.025);
    }}
    .status-item strong {{ display: block; }}
    .status-item span {{ display: block; color: var(--muted); font-size: 13px; margin-top: 3px; }}
    ul {{ margin: 0; padding-left: 20px; }}
    li + li {{ margin-top: 6px; }}
    a {{ color: inherit; }}
    footer {{
      color: var(--muted);
      margin-top: 16px;
      padding-top: 14px;
      border-top: 1px solid var(--line);
      font-size: 13px;
    }}
    @media (max-width: 780px) {{
      main {{ width: min(100vw - 22px, 560px); padding-top: 20px; }}
      header, .cards, .status-list {{ grid-template-columns: 1fr; }}
      h1 {{ font-size: 29px; }}
      .card {{ min-height: auto; }}
    }}
  </style>
</head>
<body>
  <main>
    <header>
      <div>
        <h1>{title}</h1>
        <p class="sub">{subtitle}</p>
      </div>
      <div class="badge">{badge}</div>
    </header>

    <div class="grid">
      <section>
        <h2>Use First</h2>
        <div class="cards">
{use_first}
        </div>
      </section>

      <section>
        <h2>Status By Story</h2>
        <div class="status-list">
{stories}
        </div>
      </section>
{validation_results_section}

      <section>
        <h2>Run / Token</h2>
        <div class="commands">
{command_list}
        </div>
      </section>

      <section>
        <h2>Screenshots</h2>
        <div class="cards">
{screenshot_cards}
        </div>
      </section>

      <section>
        <h2>What To Review</h2>
        <ul>
{review}
        </ul>
      </section>
    </div>

    <footer>
      {footer}
    </footer>
  </main>
</body>
</html>
"""


def is_external(href: str) -> bool:
    return href.startswith(("http://", "https://", "mailto:", "#"))


def referenced_links(manifest: dict[str, Any]) -> list[str]:
    links: list[str] = []
    for section in ("use_first", "validation_results", "screenshots"):
        for item in manifest.get(section) or []:
            href = str(item.get("href") or "")
            if href:
                links.append(href)
    return links


def validate_links(manifest_path: Path, manifest: dict[str, Any]) -> list[str]:
    base = manifest_path.parent
    missing = []
    for href in referenced_links(manifest):
        if is_external(href):
            continue
        target = (base / href).resolve()
        if not target.exists():
            missing.append(href)
    return missing


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate and validate a stable HTML deliverables hub from a story manifest.")
    parser.add_argument("manifest", type=Path, help="Path to deliverables.json.")
    parser.add_argument("--output", type=Path, default=None, help="Output HTML path. Defaults to <manifest-dir>/start-here.html.")
    parser.add_argument("--check-links", action="store_true", help="Fail if local links in the manifest do not exist.")
    parser.add_argument("--check-only", action="store_true", help="Validate manifest and links without writing HTML.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    manifest_path = args.manifest if args.manifest.is_absolute() else (ROOT / args.manifest)
    output = args.output or (manifest_path.parent / "start-here.html")
    if not output.is_absolute():
        output = ROOT / output

    manifest = load_manifest(manifest_path)
    missing = validate_links(manifest_path, manifest) if args.check_links else []
    if missing:
        print("missing local deliverable links:", file=sys.stderr)
        for href in missing:
            print(f"- {href}", file=sys.stderr)
        return 1

    if not args.check_only:
        output.write_text(render(manifest), encoding="utf-8")
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
